audit_header: false
title: DMV Real Estate Journal
description: Our mission at Local Expert Realty is to be your best resource for DC Metro Area real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Local Expert Realty, your professional DC Metro Area Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Kristy Moore
  title:
  license_number:
  about_markdown: |
    Local Expert Realty is a top producing real estate team in the metro DC area run by Broker and Founder, Kristy Moore. Prior to founding this innovative company she founded Moore Realty Services and grew it to a top producing real estate team in the metro DC area winning an award in 2015 for the Best Teams in America. Local Expert Realty’s philosophy is that ‘Performance Beats Promises’. Our statistics consistently outperform other agents in our marketplace. We get our sellers more money and our buyers better deals than any other team in the area. Our team of Realtors, marketing and lead specialists, contract administrators, and closing coordinators ensures every client receives top notch service every time. Call us today to find out how you can “Experience the Difference”.
  market: DC Metro Area
  brand: Local Expert Realty
  brokerage:
  address: 705 Park Ave, Falls Church, VA 22046
  phone: 888-297-8393
  phone_type:
  phone2:
  phone2_type:
  email: Kristy@LocalExpertRealty.com
  url: http://LocalExpertRealty.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://dmvmarketreport.com/
  second_CTA_text: Home Search
  second_CTA_URL: http://localexpertrealty.com/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your DC Metro Area Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://dmvmarketreport.com/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a DC Metro Area Home?"
    CTA_text2: "Search the entire MLS for your DC Metro Area home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://localexpertrealty.com/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: true
  facebook_url: https://www.facebook.com/LocalExpertRealty
  linkedin_url: https://www.linkedin.com/in/kristylynam/
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/klynammoore/
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'DC Metro Area Real Estate Podcast with Kristy Moore'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the DC Metro Area Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Local Expert Realty - your professional DC Metro Area Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in DC Metro Area, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Kristy Moore'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: DMV Real Estate Journal
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  theme_color: '#F26532'
  brand_color: '#1C3F95'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#ffffff'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
